scan_timeout = 60
add_newline = false

[username]
format = "[$user]($style)"
disabled = false
show_always = true
style_user = "bold green"

[hostname]
format =  " [$hostname]($style) "
ssh_only = false
disabled = false
style = "bold blue"

[line_break]
disabled = false

[directory]
# format = "$directory"
style = "bold bright-cyan"

[cmd_duration]
format = "[$duration]($style) "

[character] # The name of the module we are configuring is "character"
success_symbol = "[[\\[I\\]](bold white) ➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
vicmd_symbol = "[[\\[V\\]](bold white) ➜](bold red)"
error_symbol = "[[\\[I\\]](bold red) ➜](bold red)"

[status]
disabled = true
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[php]
format = "[$symbol($version )]($style)"
symbol = " "
disabled = true

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
